language: go

go:
    - tip

install:
    - make install

before_script:
    - make lintchecks

script:
    - make tests                        # Runs unit tests

after_success:
    - ./scripts/generate-test-coverage.sh --coveralls