language: go

go:
    - 1.8.x
    - tip

install:
    - make install
    - go get github.com/mattn/goveralls

before_script:
    - ./scripts/travis.gofmt.sh        # Fail if .go file hasn't been formatted with gofmt
    - ./scripts/travis.govet.sh        # go vet source code
    - ./scripts/travis.gometalint.sh   # gometalint all source code

script:
    #- make testcoverage         # Runs unit tests & code coverage
    - cd src && goveralls -service=travis-ci

after_success:
    - bash <(curl -s https://codecov.io/bash)