language: go

go:
    - 1.8.x

install:
    - make install

script:
    - ! gofmt -d src test 2>&1 | read
    - make testcoverage # Runs unit tests & code coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)