language: go

go:
    - tip

install:
    - make install

before_script:
    - make lintchecks

notifications:
  webhooks:
    - https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

script:
    - make tests                        # Runs unit tests

after_success:
    - ./scripts/generate-test-coverage.sh --coveralls
